
/**
  * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  * ! WARNING: This is a generated file, any modifications may be overwritten !
  * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  *
  * Generated by "merge2file"
  *
  * Date: Thu Oct 12 2017 13:47:20 GMT+0200 (CEST)
  * Export target: "./src/languages/export/fi.js"
  * Executor: jpruijs
  * Duration: 1 ms.
*/
const fi = {
  flow: {
    base: "Sivulla Luontitoiminnon",
    layout: "Kaavio",
    model: "Malli",
    page: "Sivu"
  },
  pageType: {
    layout: "PageLayout",
    model: "PageModel"
  },
  stepLabel: {
    base: "Haluatko perustaa oman uuden sivua \"{0}\" tai \"{1}\"?",
    chooseCreate: "Valinnan tai luomisen \"{0}\"",
    createNew: "Luo \"{0}\"",
    back: "Takaisin yksi aske",
    done: "Done"
  },
  stepButton: {
    createPage: "luominen ja muokkaaminen",
    done: "Create another",
    next: "seuraava",
    back: "Takaisin"
  },
  modal: {
    yes: "Kyllä",
    no: "Ei",
    cancel: "Peruuta",
    confirm: "Vahvista",
    edit: "Ennen seuraavaan vaiheeseen, voisitteko muuttaa \"{0}\" ?"
  },
  inputNew: "Kuten \"{0}\"",
  optionChoose: "kohdassa",
  insertTitle: "Valitse otsikko {0} \"{1}\""
};
module.exports = fi;