
/**
  * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  * ! WARNING: This is a generated file, any modifications may be overwritten !
  * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  *
  * Generated by "merge2file"
  *
  * Date: Mon Oct 23 2017 10:25:59 GMT+0200 (CEST)
  * Export target: "./src/languages/export/fr.js"
  * Executor: jpruijs
  * Duration: 0 ms.
*/
const fr = {
  flow: {
    base: "Assistant création de page",
    layout: "Mise en page",
    model: "Modèle",
    page: "Page"
  },
  pageType: {
    layout: "Mise en page",
    model: "Modèle"
  },
  stepLabel: {
    base: "Souhaitez-vous créer une page à partir d'une \"{0}\" ou d'un \"{1}\" ?",
    chooseCreate: "Choix ou création de \"{0}\"",
    createNew: "Création de \"{0}\"",
    back: "Retour d'une étape",
    done: "Fin"
  },
  stepButton: {
    createPage: "Créer & Modifier",
    done: "Create another",
    next: "suivant",
    back: "Retour"
  },
  modal: {
    yes: "Oui",
    no: "Non",
    cancel: "Annuler",
    confirm: "Confirmer",
    edit: "Avant de continuer à la prochaine étape, voulez-vous modifier \"{0}\" ?"
  },
  inputNew: "Titre de \"{0}\"",
  optionChoose: "choisissez",
  insertTitle: "Saisissez un titre pour {0} \"{1}\""
};
module.exports = fr;