
/**
  * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  * ! WARNING: This is a generated file, any modifications may be overwritten !
  * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  *
  * Generated by "merge2file"
  *
  * Date: Mon Oct 23 2017 10:25:59 GMT+0200 (CEST)
  * Export target: "./src/languages/export/nl.js"
  * Executor: jpruijs
  * Duration: 0 ms.
*/
const nl = {
  flow: {
    base: "Nieuwe Pagina Assistent",
    layout: "Layout",
    model: "Model",
    page: "Pagina"
  },
  pageType: {
    layout: "Pagina Opmaak",
    model: "Pagina Model"
  },
  stepLabel: {
    base: "Moet uw nieuwe pagina gebaseerd zijn op een \"{0}\" of \"{1}\"?",
    chooseCreate: "Kies of maak een \"{0}\" aan",
    createNew: "Maak een nieuwe \"{0}\" aan",
    back: "Terug naar vorige",
    done: "Einde"
  },
  stepButton: {
    createPage: "Maak en bewerk",
    done: "Maak een andere aan",
    next: "volgende",
    back: "terug"
  },
  modal: {
    yes: "Ja",
    no: "Nee",
    cancel: "Annuleer",
    confirm: "Bevestig",
    edit: "Voordat u verder gaat naar de volgende stap, wilt u \"{0}\" aanpassen?"
  },
  inputNew: "Titel nieuwe \"{0}\"",
  optionChoose: "kies",
  insertTitle: "Kies een titel voor {0} \"{1}\""
};
module.exports = nl;